### ISSUE TITLE
'Team' object has no attribute 'get_full_name'

### ISSUE THREAD

**Issue by CrisFlagg** [jmaliksi/blaseball-mike#146]
I am unable to use the get_full_name() method

```
teams = Team.load_all()
for t in teams.keys():
    tm = teams[t]
    print( tm.get_full_name() )
```

Gives me the error:
`AttributeError: 'Team' object has no attribute 'get_full_name'
`

Is this an error in the way I'm loading the teams or do I need to call the method differently?

Version: blaseball_mike-6.5.0

**Comment by Edgarware** [comment]
Hmmm, that code snippet you posted works on my install. What's your python version and OS?

**Comment by CrisFlagg** [comment]
Ubuntu 20.04.3 LTS
python version : 3.7.4

**Comment by CrisFlagg** [comment]
Fantastic, I will upgrade.
