### ISSUE TITLE
Deserialize object for idols

### ISSUE THREAD

**Issue by jmaliksi** [jmaliksi/blaseball-mike#17]
/api/getIdols

**Comment by Edgarware** [comment]
The current implementation stores them in a dict, which is unordered. This might cause problems since the order from getIdols is actually important, since it's the ranking of each player.

**Comment by jmaliksi** [comment]
oh good call. Should be fine for python 3.7+ which guarantees ordering in dicts, but I can swap the implementation explicitly to OrderedDict when I am done with lunch
