### ISSUE TITLE
Table objects don't automagically return strings

### ISSUE THREAD

**Issue by jmaliksi** [jmaliksi/blaseball-mike#23]
they are returning the table object rather than the string value

**Comment by Edgarware** [comment]
would this just be adding a __str__ implementation for the class?

**Comment by jmaliksi** [comment]
I don’t think so. We want it (i think) to work such that when you do
player.coffee it’ll return the human readable string right then and there

**Comment by jmaliksi** [comment]
Or it returns a human readable enum? Unsure
