### ISSUE TITLE
Chorby Soul's Soulscream

### ISSUE THREAD

**Issue by Edgarware** [jmaliksi/blaseball-mike#40]
Chorby Soul has a `soul` value of 1777, which breaks the code for soulscream generation. This is because the equation for soulscream attempts to calculate 10^-x with increasing x up to the soul value. This causes all kinds of problems with floating point numbers, since even with double precision you only have ~15 bits of precision. 

To top this off, Javascript doesn't really have a standard for float rounding or precision. The Soulscream displays differently on the blaseball site depending on browser, OS, and device.

I've got 2 potential fixes in my head:

1. Catch the divide-by-zero Exception when it gets too big and insert `undefined` like the javascript does. This scream will be different than what's on the site but at least it wont crash when trying to generate it.
2. Limit the length of the soulscream. Testing shows the data matches for soul iterations of 23 and lower (or 253 characters). This scream will be much different than the site, but any additional characters we generate would be incorrect.

**Comment by jmaliksi** [comment]
i like matching the javascript with the `undefined`

it's kinda funny how the soul scream is different everywhere
