### ISSUE TITLE
Dynamically load weather, attributes, weather

### ISSUE THREAD

**Issue by jmaliksi** [jmaliksi/blaseball-mike#51]
can load from here: https://github.com/xSke/blaseball-site-files/tree/main/data

will likely be a breaking change to go from enum to json

**Comment by jmaliksi** [comment]
blood and coffee can be loaded from here
https://www.blaseball.com/database/coffee?ids=a,b,c,d,e,f,g,h,i,j,k
https://www.blaseball.com/database/blood?ids=0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15

**Comment by Edgarware** [comment]
This is completed for everything except for Weather (which doesn't have an endpoint from what we can tell) and the Tarot cards (which will probably never change so we're fine keeping it static)

**Comment by jmaliksi** [comment]
nice, closing
