### ISSUE TITLE
Split up models to their own files

### ISSUE THREAD

**Issue by jmaliksi** [jmaliksi/blaseball-mike#84]
Could be done without a breaking change by turning `models.py` into a folder containing a file for each class, then loading them into the module `__init__`

**Comment by Edgarware** [comment]
Heck yes. As part of this we should probably also import stuff into the top-level module, so people can just do `from blaseball-mike import Player`.

**Comment by Edgarware** [comment]
oh no. *circular imports*.

**Comment by jmaliksi** [comment]
yeah i thought about that, you can move the import into the methods and it'll be fine. fun fact about python imports is that imported modules are stored by a global dict, so once you import it won't do things twice and also since it's just a dict you can do a lot of shenanigans if you are feeling cheeky and it's Bad

**Comment by Edgarware** [comment]
lol it's cool. The only big problems are the Statsheets and the Team<->Player stuff.
